export const styles = {
    body: {
        backgroundColor: '#f3f4f6',
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    },
    container: {
        backgroundColor: '#ffffff',
        margin: '40px auto',
        padding: '0',
        borderRadius: '8px',
        overflow: 'hidden',
        border: '1px solid #e5e7eb',
        maxWidth: '600px',
    },
    header: {
        padding: '32px',
        textAlign: 'center' as const,
    },
    brand: {
        fontSize: '30px',
        fontWeight: 'bold',
        color: '#ffffff',
        margin: '0',
    },
    subtitle: {
        color: '#d1d5db',
        textTransform: 'uppercase' as const,
        letterSpacing: '2px',
        fontSize: '10px',
        marginTop: '8px',
    },
    content: {
        padding: '32px',
    },
    greeting: {
        textAlign: 'center' as const,
        marginBottom: '24px',
    },
    successTitle: {
        color: '#16a34a',
        fontSize: '20px',
        fontWeight: 'bold',
        margin: '0 0 8px',
    },
    text: {
        color: '#4b5563',
        fontSize: '16px',
        margin: '0',
    },
    card: {
        backgroundColor: '#f9fafb',
        borderRadius: '12px',
        padding: '24px',
        marginBottom: '32px',
        border: '1px solid #f3f4f6',
    },
    row: {
        marginBottom: '16px',
    },
    label: {
        color: '#6b7280',
        fontSize: '12px',
        textTransform: 'uppercase' as const,
        fontWeight: 'bold',
        margin: '0 0 4px',
    },
    code: {
        fontSize: '24px',
        fontFamily: 'monospace',
        fontWeight: 'bold',
        color: '#1f2937',
        margin: '0',
        letterSpacing: '1px',
    },
    badge: {
        fontSize: '14px',
        fontWeight: 'bold',
        padding: '4px 12px',
        borderRadius: '9999px',
        display: 'inline-block',
        margin: '0',
    },
    divider: {
        borderTop: '1px solid #e5e7eb',
        margin: '16px 0',
    },
    value: {
        color: '#1f2937',
        fontSize: '16px',
        fontWeight: '500',
        margin: '0',
    },
    subtext: {
        color: '#9ca3af',
        fontSize: '12px',
        margin: '0',
    },
    sectionTitle: {
        fontSize: '18px',
        fontWeight: 'bold',
        color: '#1f2937',
        borderBottom: '1px solid #f3f4f6',
        paddingBottom: '8px',
        marginBottom: '16px',
    },
    roomItem: {
        backgroundColor: '#f9fafb',
        padding: '12px 16px',
        borderRadius: '6px',
        color: '#4b5563',
        marginBottom: '8px',
        margin: '0 0 8px',
    },
    labelRow: {
        color: '#6b7280',
        fontSize: '14px',
        margin: '0',
    },
    valueRow: {
        color: '#1f2937',
        fontSize: '14px',
        fontWeight: '500',
        margin: '0',
    },
    labelRowSmall: {
        color: '#9ca3af',
        fontSize: '12px',
        margin: '0',
    },
    totalLabel: {
        color: '#1f2937',
        fontSize: '16px',
        fontWeight: 'bold',
        margin: '0',
    },
    totalValue: {
        color: '#1f2937',
        fontSize: '16px',
        fontWeight: 'bold',
        margin: '0',
    },
    paymentBox: {
        backgroundColor: '#ffffff',
        padding: '12px',
        borderRadius: '6px',
        border: '1px solid #e5e7eb',
        marginTop: '8px',
    },
    paidLabel: {
        color: '#16a34a',
        fontSize: '14px',
        fontWeight: 'bold',
        margin: '0',
    },
    paidValue: {
        color: '#16a34a',
        fontSize: '14px',
        fontWeight: 'bold',
        margin: '0',
    },
    pendingLabel: {
        color: '#ef4444',
        fontSize: '14px',
        fontWeight: 'bold',
        margin: '0',
    },
    pendingValue: {
        color: '#ef4444',
        fontSize: '14px',
        fontWeight: 'bold',
        margin: '0',
    },
    button: {
        backgroundColor: '#27272a',
        color: '#ffffff',
        padding: '12px 24px',
        borderRadius: '6px',
        fontSize: '14px',
        fontWeight: '500',
        textDecoration: 'none',
        display: 'inline-block',
    },
    footer: {
        backgroundColor: '#f9fafb',
        padding: '16px',
        textAlign: 'center' as const,
        borderTop: '1px solid #f3f4f6',
    },
    footerText: {
        color: '#9ca3af',
        fontSize: '12px',
        margin: '16px 0 0',
    }
};
